package ihm;

import application.CustomFilter;
import database.DaoPhoto;
import java.io.File;
import javax.swing.JOptionPane;
import metier.Photo;

public class InsertPhoto extends javax.swing.JDialog
{

    private final Photo photo;
    private boolean etatSortie;
    private String nomFichier = "";

    public InsertPhoto(java.awt.Frame parent, Photo photo)
    {
        super(parent, true);
        initComponents();
        this.photo = photo;
        this.setLocation(parent.getLocation());
        etatSortie = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean doModal()
    {
        setVisible(true);
        return etatSortie;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnAdd = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        textPlacePhoto = new javax.swing.JTextField();
        lbLName = new javax.swing.JLabel();
        lbLName1 = new javax.swing.JLabel();
        textYearPhoto = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();

        jFileChooser1.setApproveButtonText("Upload");
        jFileChooser1.setFileFilter(new CustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnAdd.setText("ADD");
        btnAdd.setMaximumSize(new java.awt.Dimension(77, 25));
        btnAdd.setMinimumSize(new java.awt.Dimension(77, 25));
        btnAdd.setPreferredSize(new java.awt.Dimension(77, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Title.setText("Insert Photo");

        textPlacePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlacePhotoActionPerformed(evt);
            }
        });

        lbLName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLName.setText("place photo");

        lbLName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLName1.setText("year photo");

        textYearPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYearPhotoActionPerformed(evt);
            }
        });

        btnAdd1.setText("Choose photo");
        btnAdd1.setMaximumSize(new java.awt.Dimension(77, 25));
        btnAdd1.setMinimumSize(new java.awt.Dimension(77, 25));
        btnAdd1.setPreferredSize(new java.awt.Dimension(77, 25));
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPlacePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textYearPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(btnAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLName)
                    .addComponent(textPlacePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLName1)
                    .addComponent(textYearPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPlacePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlacePhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlacePhotoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try
        {            
            String placePhoto = textPlacePhoto.getText();
            if (placePhoto.isEmpty())
            {
                throw new Exception("Field of place empty");
            }
            photo.setPlacePhoto(placePhoto);            
            
            int yearPhoto = Integer.parseInt(textYearPhoto.getText());
            String photoYearHelper = textYearPhoto.getText();
            if (photoYearHelper.isEmpty())
            {
                throw new Exception("Field year empty");
            }
            photo.setYearPhoto(yearPhoto);

            
            
            if (nomFichier.equals("")) {
                throw new Exception("Error upload photo");
            }
            photo.setWayPhoto("/assets/images/VIP/" + nomFichier);
            
            etatSortie = true;
            this.dispose();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void textYearPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYearPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYearPhotoActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            nomFichier = DaoPhoto.send(file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lbLName;
    private javax.swing.JLabel lbLName1;
    private javax.swing.JTextField textPlacePhoto;
    private javax.swing.JTextField textYearPhoto;
    // End of variables declaration//GEN-END:variables
}
