package ihm;

import javax.swing.JOptionPane;
import metier.Tag;

public class InsertTag extends javax.swing.JDialog
{

    private final Tag tag;
    private boolean etatSortie;

    public InsertTag(java.awt.Frame parent, Tag tag)
    {
        super(parent, true);
        initComponents();
        this.tag = tag;
        this.setLocation(parent.getLocation());
        etatSortie = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean doModal()
    {
        setVisible(true);
        return etatSortie;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnAdd = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        textNumVip = new javax.swing.JTextField();
        textNumPhoto = new javax.swing.JTextField();
        lbFName = new javax.swing.JLabel();
        lbLName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnAdd.setText("ADD");
        btnAdd.setMaximumSize(new java.awt.Dimension(77, 25));
        btnAdd.setMinimumSize(new java.awt.Dimension(77, 25));
        btnAdd.setPreferredSize(new java.awt.Dimension(77, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Title.setText("Insert Tag");

        textNumVip.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textNumVipActionPerformed(evt);
            }
        });

        textNumPhoto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textNumPhotoActionPerformed(evt);
            }
        });

        lbFName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFName.setText("num VIP");

        lbLName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLName.setText("num Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLName)
                            .addComponent(lbFName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNumVip, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFName)
                    .addComponent(textNumVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLName)
                    .addComponent(textNumPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumVipActionPerformed

    private void textNumPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumPhotoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try
        {
            int numVip = Integer.parseInt(textNumVip.getText());
            String vipHelper = textNumVip.getText();
            if (vipHelper.isEmpty())
            {
                throw new Exception("Field vip empty");
            }
            tag.setNumVIP(numVip);

            
            int numPhoto = Integer.parseInt(textNumPhoto.getText());
            String photoHelper = textNumPhoto.getText();
            if (photoHelper.isEmpty())
            {
                throw new Exception("Field photo empty");
            }
            tag.setNumPhoto(numPhoto);

            etatSortie = true;
            this.dispose();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lbFName;
    private javax.swing.JLabel lbLName;
    private javax.swing.JTextField textNumPhoto;
    private javax.swing.JTextField textNumVip;
    // End of variables declaration//GEN-END:variables
}
