/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

/**
 *
 * @author EtiX42
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        AjoutVIP = new javax.swing.JButton();
        SupprimerVIP = new javax.swing.JButton();
        InsertMariage = new javax.swing.JButton();
        InsertDivorce = new javax.swing.JButton();
        Titre = new javax.swing.JLabel();
        ModifierVIP = new javax.swing.JButton();

        jButton4.setText("Insérer mariage");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        AjoutVIP.setText("Ajouter VIP");
        AjoutVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutVIPActionPerformed(evt);
            }
        });

        SupprimerVIP.setText("Supprimer VIP");
        SupprimerVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerVIPActionPerformed(evt);
            }
        });

        InsertMariage.setText("Insérer mariage");
        InsertMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMariageActionPerformed(evt);
            }
        });

        InsertDivorce.setText("Insérer divorce");
        InsertDivorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertDivorceActionPerformed(evt);
            }
        });

        Titre.setText("Application VIP");

        ModifierVIP.setText("Modifier VIP");
        ModifierVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierVIPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ModifierVIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AjoutVIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SupprimerVIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InsertDivorce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertMariage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(Titre)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutVIP)
                    .addComponent(InsertMariage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModifierVIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertDivorce)
                    .addComponent(SupprimerVIP))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjoutVIPActionPerformed

    private void SupprimerVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupprimerVIPActionPerformed

    private void InsertMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMariageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertMariageActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void InsertDivorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertDivorceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertDivorceActionPerformed

    private void ModifierVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierVIPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutVIP;
    private javax.swing.JButton InsertDivorce;
    private javax.swing.JButton InsertMariage;
    private javax.swing.JButton ModifierVIP;
    private javax.swing.JButton SupprimerVIP;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
